### PR TITLE
APH Fix

### LINKED ISSUE #9: Adding APH
Right now there's a problem when changing the APH value in our demo at https://harvestprofit.github.io/what-if-analysis/

Due to some string/number issues, when feeding in the APH to the `WhatIfTable` component in our Demo. When changing the APH value, the values increment unevenly (look at the left-most column):
screen shot 2018-04-21 at 5 03 35 pm

### PR DESCRIPTION
**Pull request by cody-elhard**
Added handleChange() function to input

Typecast input from String to Float

Closes #9

### CODE REVIEW

File: demo/src/input.js [hunk 1]
```diff
@@ -15,6 +15,17 @@ class Input extends Component {
     help: PropTypes.string.isRequired,
   }
 
+  constructor (props) {
+    super(props);
+    this.handleChange = this.handleChange.bind(this);
+  }
+
+  handleChange(event) {
+    const intTargetValue = parseFloat(event.target.value);
```
Comment (jarydkrish) [inline demo/src/input.js]: Could we change this to a different variable name? This variable is a float, I presume?
